### ISSUE TITLE
Secretstorage fails to install on Ubuntu 16.04

### ISSUE THREAD

**Issue by BenjamenMeyer** [mitya57/secretstorage#5] opened 2016-06-27 15:42 UTC
Secretstorage as of version 2.2.0 is trying to install python-dbus; however, this causes an installation failure on Ubuntu 16.04 as the dbus-1 package is no more, it's just dbus, and at least intermediate dependencies have not been updated to reflect this change.

FYI - python-dbus is not pip installable, and seems to be a system-level package. Do you really need dbus access? I suspect many user may not - in my case, I'm working on a RESTful API and secretstorage got pulled in by a dependency we won't have dbus running on our servers; might be good to make this optional for 2.2.1 or 2.3.

**Comment by mitya57** [comment] 2016-06-27 19:23
Hi, I think this is a duplicate of #4, and is already fixed in Git.

I just want to provide some clarification:
- SecretStorage really needs dbus-python, it won't function without it.
- You can install dbus-python from Ubuntu repos (packages `python-dbus` and `python3-dbus`), then you won't need to install it from PyPI (actually, you can install SecretStorage itself from Ubuntu repos too).
- When installing dbus-python from PyPI, it needs to be compiled from source.
- For compilation, it needs a `dbus-1` pkg-config package (i.e. a `dbus-1.pc` file). On Ubuntu, it is provided in `libdbus-1-dev` package. One will need `dbus-glib-1.pc` from `libdbus-glib-1-dev` package too.

**Closed by mitya57** 2016-06-27 19:23 UTC

**Comment by BenjamenMeyer** [comment] 2016-06-29 04:56
SecretStorage should *not* need dbus-python to function. You didn't require it in prior versions so it should be doable to support it as an optional dependency.

Agreed #4 is the same issue - I didn't see it; however, requiring dbus to access a non-existent keyring on a server doesn't make sense. This only makes sense on a Desktop-side tool, thus why I say it should be optional.

I have no need for dbus nor adding a full-fledge keyring like GNOME Keyring or the KDE equivalent.

I'll attempt to use the new 2.2.1 release and see if that fixes my issue, but installing dbus is not an option.

**Comment by mitya57** [comment] 2016-06-29 05:12
SecretStorage still **does** need dbus-python (after all Secret Service is a D-Bus based protocol). In previous versions it was not a dependency because it didn't have a setup.py file and thus was not installable from PyPI.
